import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { withSSRContext } from 'aws-amplify'
import { Authenticator } from '@aws-amplify/ui-react'

export default function Home({creds}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Authenticator>
        {({signOut, user}) => (
          <div>
            <h1 className={styles.title}>Welcome to <a href="https://nextjs.org">Next.js!</a></h1>
            <p>{user.username}</p>
            <div className={styles.grid}>
              <div className={styles.card}>
                <h2>Creds</h2>
                <p>{creds}</p>
              </div>
            </div>
            <div className={styles.card}>
              <button onClick={signOut}>Sign Out</button>
            </div>
          </div>
        )
        }
        </Authenticator>
      </main>

      <footer className={styles.footer}>
        <p>Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </p>
      </footer>
    </div>
  )
}


export async function getServerSideProps({ req }) {
  const SSR = withSSRContext({ req });

  let creds;

  try {
    creds = await SSR.Auth.currentCredentials()
  } catch(e){
    creds = e
  }

  console.log();

  return {
    props: {
      creds: JSON.stringify(creds)
    }
  }
}

// aws ecr get-login-password --profile dkkiuna --region us-east-1 | docker login --username AWS --password-stdin 524405517764.dkr.ecr.us-east-1.amazonaws.com